### PR TITLE
Optimize the SourceGenTypeShapeProvider.GetTypeShape method.

### LINKED ISSUE #252: Source generated type shape provider loads all assemblies for shaped types when only one is requested
In adopting this in Visual Studio, we noticed unexpected assembly loads on startup when migrating to PolyType. Here is what I found as the blame when I wrote an assembly load test:

```
System.Exception : Assembly System.Numerics was loaded unexpectedly by the test with this stack trace: 
   at PolyType.SourceGenerator.ShapeProvider_Nerdbank_MessagePack_Tests.GetShape(Type type)
   at PolyType.Abstractions.TypeShapeProvider.Resolve(ITypeShapeProvider shapeProvider, Type type)
   at PolyType.Utilities.TypeCache.GetOrAdd(Type type)
   at Nerdbank.MessagePack.PolyfillExtensions.GetOrAddOrThrow(MultiProviderTypeCache cache, Type type, ITypeShapeProvider provider) in D:\source\repos\Nerdbank.MessagePack\src\Nerdbank.MessagePack\PolyfillExtensions.cs:line 47
   at Nerdbank.MessagePack.ConverterCache.GetOrAddConverter[T](ITypeShapeProvider provider) in D:\source\repos\Nerdbank.MessagePack\src\Nerdbank.MessagePack\ConverterCache.cs:line 130
   at Nerdbank.MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T& value, ITypeShapeProvider provider, CancellationToken cancellationToken) in D:\source\repos\Nerdbank.MessagePack\src\Nerdbank.MessagePack\MessagePackSerializer.cs:line 256
   at Nerdbank.MessagePack.MessagePackSerializer.Serialize[T](T& value, ITypeShapeProvider provider, CancellationToken cancellationToken) in D:\source\repos\Nerdbank.MessagePack\src\Nerdbank.MessagePack\MessagePackSerializer.FriendlyOverloads.cs:line 124
   at MessagePackSerializerPolyfill.Serialize[T](MessagePackSerializer serializer, T& value, CancellationToken cancellationToken) in D:\source\repos\Nerdbank.MessagePack\test\Nerdbank.MessagePack.Tests\MessagePackSerializerPolyfill.cs:line 11
   at AssemblyLoadTests.AppDomainTestDriver.SerializeSomethingSimple() in D:\source\repos\Nerdbank.MessagePack\test\Nerdbank.MessagePack.Tests\AssemblyLoadTests.cs:line 81
```

It appears the source generated type shape provider has one massive `GetShape(Type)` method that references every single type for which we have a source generated shape. Very large methods take a long time to JIT, but more importantly every type reference in a given method must be resolved (and assembly loaded) before the method can execute, regardless of the paths that method's execution might take.

I took steps to avoid an assembly load problem like this in my source generated `GetAssociatedTypeShape` method by converting the input `Type` to a string and then implementing the method as a switch statement over the string, calling into other methods for each type shape 'factory' based on that string, so that the JIT doesn't need to load any unrelated assemblies. We could potentially apply that here. One complication with the string approach is whether to include the assembly name of the type, since including it can cause mismatches in the case of type forwarding and excluding it can cause type collisions where there are none. But I suspect we could work something out (e.g. disambiguate on type name collisions by loading colliding assemblies at that point).

Another option might be to use a `ITypeShapeProvider.Resolve<T>` method, which is the strategy that Nerdbank.MessagePack itself uses to avoid loading converters and types that are not necessary. This works because the JIT can tell at invocation time how `if` checks will evaluate and only loads the types necessary. We might test this more thoroughly to make sure it's true in all cases though (e.g. across ref types rather than just value types).

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Fix #252.

### CODE REVIEW

File: src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs [hunk 1]
```diff
@@ -55,24 +55,56 @@ private static void FormatGetShapeProviderMethod(TypeShapeProviderModel provider
             /// <inheritdoc/>
             public override global::PolyType.ITypeShape? GetTypeShape(global::System.Type type)
             {
+                // This method looks up type shapes from the full transitive type graph
```
Comment (eiriktsarpalis) [inline src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs]: @AArnott would there be any downsides to applying the same strategy in the AssociatedTypes lookup method that current accepts string?

File: src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs [hunk 2]
```diff
@@ -55,24 +55,56 @@ private static void FormatGetShapeProviderMethod(TypeShapeProviderModel provider
...
 
-        writer.Indentation++;
-
-        foreach (TypeShapeModel generatedType in provider.ProvidedTypes.Values)
+        writer.Indentation += 2;
+        foreach (var grouping in provider.ProvidedTypes.Values.GroupBy(t => t.ReflectionName).OrderBy(t => t.Key))
         {
             writer.WriteLine($$"""
-                if (type == typeof({{generatedType.Type.FullyQualifiedName}}))
+                case {{FormatStringLiteral(grouping.Key)}}:
```
Comment (AArnott) [inline src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs]: Will this lead us to group `List<int>` together with `List<BigInteger>`? It seems your `ReflectionName` will only be `List``1` in that case. That will defeat your efforts to defer unwanted assembly loads in some cases. Can we do better?

File: src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs (hunk 1 above)
Comment (AArnott) [reply src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs]: Associated type lookup is very typically based on _open_ generic types, while the shapes they return are of course closed. We'll need to make sure that continues to work.

File: src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs (hunk 2 above)
Comment (eiriktsarpalis) [reply src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs]: Only if we use something akin to `Type.FullName` in the string comparison step. It's possible, but it also comes with performance ramifications.

Comment (eiriktsarpalis) [reply src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.TypeShapeProvider.cs]: I've tweaked the strategy to use the `Type.ToString()` format which seems concise enough for our purposes.

File: src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.cs [hunk 3]
```diff
@@ -203,22 +203,60 @@ string GetElementTypeFQN() => valueType is { } vt
...
+    }
 
-        StringBuilder builder = new();
-        builder.Append("static associatedType => associatedType switch { ");
+    private void FormatAssociatedTypesFactory(SourceWriter writer, TypeShapeModel objectShapeModel, string factoryName)
+    {
+        Debug.Assert(objectShapeModel.AssociatedTypes.Count > 0);
+
+        writer.WriteLine($$"""
+            private global::PolyType.ITypeShape? {{factoryName}}(global::System.Type associatedType)
```
Comment (eiriktsarpalis) [inline src/PolyType.SourceGenerator/SourceFormatter/SourceFormatter.cs:216]: @AArnott heads up, I've also updated the associated shapes get method to use the same generation strategy as ITypeShapeProvider.

**Comment by AArnott** [comment]
@eiriktsarpalis Were you expecting this to break anybody? It made a type shape that was previously obtainable, unobtainable:

https://github.com/AArnott/Nerdbank.MessagePack/actions/runs/17595139070/job/49985466545?pr=608#step:6:39
